export const SET_LOADING = 'SET_LOADING'
export const SET_DOC_INFO = 'SET_DOC_INFO'
export const SET_MENU_DATA = 'SET_MENU_DATA'
export const SET_NORMAL = 'SET_NORMAL'
export const SET_DOC_DATA = 'SET_DOC_DATA'